swagger: '2.0'
# the domain of the service
host: api.upcontent.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
security:
  type: "apiKey"
  name: "Authorization"
  in: "header"
info:
  title: UpContent Platform API
  description: UpContent content discovery platform API.
  version: "1.0.0"
paths:
  # $ref: "http://spec.upcontent.com/upc/path/index.yaml"
  /infomous-graph:
    $ref: 'http://spec.upcontent.com/upc/path/infomous.yaml'

  /diagnostics/heartbeat:
    $ref: 'http://spec.upcontent.com/upc/path/diagnostics.yaml'

  /payment-forcast:
    $ref: 'http://spec.upcontent.com/upc/path/paymentForcast.yaml'

  /payment-history:
    $ref: 'http://spec.upcontent.com/upc/path/paymentHistory.yaml'

  /payment-method:
    $ref: 'http://spec.upcontent.com/upc/path/paymentMethod.yaml'

  /hootsuite.sessions:
    $ref: 'http://spec.upcontent.com/upc/path/hootsuiteSession.yaml'

  /sessions:
    $ref: 'http://spec.upcontent.com/upc/path/sessions.yaml'

  /sessions/{session_id}:
    $ref: 'http://spec.upcontent.com/upc/path/sessionsID.yaml'

  /states/{p_id}:
    $ref: 'http://spec.upcontent.com/upc/path/statesID.yaml'

  /subscription:
    $ref: 'http://spec.upcontent.com/upc/path/subscription.yaml'

  /suggestions/{suggestion_id}:
    $ref: 'http://spec.upcontent.com/upc/path/suggestionsID.yaml'

  /influence-graph/{topic_id}:
    $ref: 'http://spec.upcontent.com/upc/path/influenceID.yaml'

  /reset-token:
    $ref: 'http://spec.upcontent.com/upc/path/resetToken.yaml'

  /connect-token:
    $ref: 'http://spec.upcontent.com/upc/path/connectToken.yaml'

  /merge-token:
    $ref: 'http://spec.upcontent.com/upc/path/mergeToken.yaml'

  /topics:
    $ref: 'http://spec.upcontent.com/upc/path/topics.yaml'

  /topics/{topic_id}:
    $ref: 'http://spec.upcontent.com/upc/path/topicsID.yaml'

  /topics/{topic_id}/Suggestions:
    $ref: 'http://spec.upcontent.com/upc/path/topicsIDSuggestions.yaml'

  /active-topics:
    $ref: 'http://spec.upcontent.com/upc/path/activeTopics.yaml'

  /topic-count:
    $ref: 'http://spec.upcontent.com/upc/path/topicCount.yaml'

  /bookmarked-topics:
    $ref: 'http://spec.upcontent.com/upc/path/bookmarkedTopics.yaml'

  /bookmarked-topics/{topic_id}:
    $ref: 'http://spec.upcontent.com/upc/path/bookmarkedTopicsID.yaml'

  /users:
    $ref: 'http://spec.upcontent.com/upc/path/users.yaml'

  /users/{user_id}:
    $ref: 'http://spec.upcontent.com/upc/path/usersID.yaml'

  /confirmation/{email_token}:
    $ref: 'http://spec.upcontent.com/upc/path/confirmation.yaml'

  /password:
    $ref: 'http://spec.upcontent.com/upc/path/resetPassword.yaml'

  /change-password:
    $ref: 'http://spec.upcontent.com/upc/path/changePassword.yaml'

  /me:
    $ref: 'http://spec.upcontent.com/upc/path/me.yaml'

  /upcontent.users/{user_id}:
    $ref: 'http://spec.upcontent.com/upc/path/upcontentUsers.yaml'

  /connections:
    $ref: 'http://spec.upcontent.com/upc/path/connections.yaml'

  /user_count:
    $ref: 'http://spec.upcontent.com/upc/path/userCount.yaml'
definitions:
  $ref: 'http://spec.upcontent.com/upc/definitions/index.yaml'
